DROP SCHEMA IF EXISTS account_requests CASCADE;
DROP SCHEMA IF EXISTS credentials CASCADE;
DROP SCHEMA IF EXISTS groups CASCADE;
DROP SCHEMA IF EXISTS laboral_insertion CASCADE;
DROP SCHEMA IF EXISTS profile CASCADE;
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS students CASCADE;
DROP SCHEMA IF EXISTS system CASCADE;
DROP SCHEMA IF EXISTS systems CASCADE;

